baseURL = 'https://wirtaw.github.io/blog'
languageCode = 'en-us'
title = 'Poplavskij Vladimir blog'
theme = 'typo'
publishDir = "."

[params]
homeIntroTitle = 'Hi!'

homeIntroContent = """
I am Lithuanian is a highly skilled Senior Backend Developer with a proven track record of success in various roles. 
With expertise in JavaScript, databases, Linux, CSS, and PHP.
 Have excelled in seamless integration with third-party and internal services, maintenance of production services, database optimization, and observability enhancement.
"""

[[params.social]]
name = "github"
url = "https://github.com/wirtaw"

[[params.social]]
name = "bitbucket"
url = "https://bitbucket.org/wirtaw/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/wirtaw/"

[[params.menu]]
name = "home"
url = "/blog/"

[[params.menu]]
name = "posts"
url = "/blog/posts"